import { describe, expect, test } from "bun:test";
import { MCP_CATALOG } from "@bai/shared";
import { MCP_FALLBACKS, MCP_ICONS } from "../src/mcp-icons";

/**
 * `src/mcp-icons.ts` is generated by `scripts/generate-mcp-icons.mjs`; this
 * guards against adding a catalog entry without an icon (run
 * `bun run generate:icons` to regenerate).
 */
describe("MCP brand icons", () => {
  test("every catalog entry resolves to a brand icon or a lucide fallback", () => {
    for (const entry of MCP_CATALOG) {
      const resolved = MCP_ICONS[entry.name] !== undefined || MCP_FALLBACKS[entry.name] !== undefined;
      expect(resolved).toBe(true);
    }
    expect(Object.keys(MCP_ICONS).length + Object.keys(MCP_FALLBACKS).length).toBe(MCP_CATALOG.length);
  });

  test("brand icons carry a viewBox and body", () => {
    for (const icon of Object.values(MCP_ICONS)) {
      expect(icon.viewBox.startsWith("0 0 ")).toBe(true);
      expect(icon.body.length).toBeGreaterThan(0);
      // Monochrome contract: no embedded hex fills (inherits currentColor).
      expect(icon.body.includes('fill="#')).toBe(false);
    }
  });
});
